path: E:\code part 2\PROJECTS\Computer Vision\data  # dataset root dir - has to be an absolute path
train: images/train # train images (relative to 'path')
val: images/train # val images (relative to 'path')


# Classes
names: 
  0: alpaca